// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQv-gTvz2BlQw3MutmhwsG0dbgndcT_cc',
    appId: '1:1037267385165:web:4da83b7a302a71e240d504',
    messagingSenderId: '1037267385165',
    projectId: 'climbmetrics',
    authDomain: 'climbmetrics.firebaseapp.com',
    storageBucket: 'climbmetrics.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNa32GRtePdDoB2t03EVx5u_01abXGuRM',
    appId: '1:1037267385165:android:9420c8c1ae4c428a40d504',
    messagingSenderId: '1037267385165',
    projectId: 'climbmetrics',
    storageBucket: 'climbmetrics.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSj6Qux831zR6g5_sYmq3dHYfnmPgLrDQ',
    appId: '1:1037267385165:ios:a34e361464dd0b8440d504',
    messagingSenderId: '1037267385165',
    projectId: 'climbmetrics',
    storageBucket: 'climbmetrics.firebasestorage.app',
    iosBundleId: 'com.example.climbmetrics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSj6Qux831zR6g5_sYmq3dHYfnmPgLrDQ',
    appId: '1:1037267385165:ios:a34e361464dd0b8440d504',
    messagingSenderId: '1037267385165',
    projectId: 'climbmetrics',
    storageBucket: 'climbmetrics.firebasestorage.app',
    iosBundleId: 'com.example.climbmetrics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQv-gTvz2BlQw3MutmhwsG0dbgndcT_cc',
    appId: '1:1037267385165:web:b3d6aafcbf4b6b0640d504',
    messagingSenderId: '1037267385165',
    projectId: 'climbmetrics',
    authDomain: 'climbmetrics.firebaseapp.com',
    storageBucket: 'climbmetrics.firebasestorage.app',
  );

}